/**
 * Run: node --test .github/scripts/*.test.mjs
 *
 * This pipeline's failure mode is silence. It ran on a schedule for months, produced
 * nothing, and nobody noticed — so these tests are aimed at the three ways that happens:
 * the manifest rule that fails a source it shouldn't, a run that leaves no trace, and a
 * gate that reports "unchanged" when it has no idea.
 *
 * The fetch path is exercised against a real local HTTP server rather than mocked, so
 * a change to the fetch step is caught here instead of on a Monday morning.
 */

import { test, describe, before, after } from 'node:test'
import assert from 'node:assert/strict'
import { createServer } from 'node:http'
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, existsSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'

import { parseSources, check, sha256, byteLength, readFingerprint, renderLogEntry, insertLogEntry } from './refresh-context.mjs'

// A manifest shaped like the real one — one cached source, one live pointer, one
// deliberately unreachable, one with a hand-maintained copy. Every skip rule, once.
const manifest = (fetchUrl) => `
team: webapp

sources:
  h2_planning:
    canonical: "https://docs.example/doc"
    type: google_doc
    owner: "VP Product — not this team"
    reachable: true
    fetch: "${fetchUrl}"
    refresh: quarterly
    summarize_to: team/_generated/h2-planning.md
    last_confirmed: 2026-08-05
    notes: >
      Authored a level up. Regenerate rather than editing in place —
      maintaining a second copy of somebody else's document is a race you lose.

  cohort_scheduling_flow:
    canonical: "https://figma.example/file"
    type: figma
    owner: "Ines Okafor (Design)"
    reachable: true # via Figma MCP
    refresh: live
    last_confirmed: 2026-08-05

  product_backlog:
    canonical: "https://jira.example/board"
    type: jira_project
    reachable: true
    last_confirmed: 2026-08-16

  vendor_video_sla:
    canonical: "vendor portal, SSO only — no API"
    type: vendor_portal
    reachable: false
    copy_of_record: insights/vendor-video-sla-2026-q3.md
    refresh: quarterly

  restricted_source:
    canonical: "Legal, counsel only"
    type: restricted
    reachable: false
    deliberate: true

local:
  - product/decisions/
`

// The body the test server returns from /doc. Kept at module scope because the
// fingerprint tests need to hash exactly what the server will serve.
const DOC_BODY = 'H2 2026 planning. Target: 40% of cohorts full at start. Owner: VP Product.'

// A generated file the way /refresh-index writes one — what matters here is the
// fingerprint line, which is the only state the whole gate keeps.
const generated = (sha, bytes) => `<!-- Generated from https://docs.example/doc
     by /refresh-index on 2026-08-19.
     Source fingerprint: sha256:${sha} (${bytes} bytes)
     Do not edit this file. Edit the source, or the manifest entry that points at it. -->

> **Generated file.** Summarized from the google doc owned by VP Product, on 2026-08-19.

# H2 planning

Target: 40% of cohorts full at start.
`

describe('parseSources — the manifest reader', () => {
  const sources = parseSources(manifest('https://example.test/doc'))

  test('reads every source and stops at the next top-level key', () => {
    assert.deepEqual(Object.keys(sources), [
      'h2_planning',
      'cohort_scheduling_flow',
      'product_backlog',
      'vendor_video_sla',
      'restricted_source',
    ])
  })

  test('an inline comment is not part of the value', () => {
    // `reachable: true # via Figma MCP` has to come back as the boolean true, not the
    // string "true # via Figma MCP", which is truthy and would silently pass every check.
    assert.equal(sources.cohort_scheduling_flow.reachable, true)
    assert.equal(sources.restricted_source.reachable, false)
    assert.equal(sources.restricted_source.deliberate, true)
  })

  test('a folded block comes back as one line', () => {
    assert.match(sources.h2_planning.notes, /^Authored a level up\..*race you lose\.$/)
  })
})

describe('the cached-or-pointed-at rule', () => {
  let dir

  before(() => {
    dir = mkdtempSync(join(tmpdir(), 'refresh-'))
    process.chdir(dir)
  })

  const setup = (yaml) => {
    writeFileSync(join(dir, 'context-manifest.yaml'), yaml)
    mkdirSync(join(dir, 'team/_generated'), { recursive: true })
  }

  test('`refresh: live` on a pointed-at source is correct, not a failure', async () => {
    // This is the bug that kept the pipeline from ever opening a PR. `live` is the one
    // refresh value that means "there is deliberately no copy" — demanding a path from
    // it inverts what it says, and the exit code it produced killed the PR step.
    setup(manifest('https://127.0.0.1:1/unused'))
    const { failed } = await check({ dryRun: true, today: '2026-08-19' })
    assert.equal(
      failed.some((f) => f.name === 'cohort_scheduling_flow'),
      false,
      'a live pointer must not be reported as a manifest error',
    )
  })

  test('a real cadence with nowhere to write still fails', async () => {
    setup(manifest('https://127.0.0.1:1/unused').replace('refresh: live', 'refresh: weekly'))
    const { failed } = await check({ dryRun: true, today: '2026-08-19' })
    const f = failed.find((x) => x.name === 'cohort_scheduling_flow')
    assert.ok(f, 'a cadence on a source with no path is somebody assuming a copy exists')
    assert.match(f.why, /names no file in this repo/)
  })

  test('each kind of skip says which kind it is', async () => {
    setup(manifest('https://127.0.0.1:1/unused'))
    const { skipped } = await check({ dryRun: true, today: '2026-08-19' })
    const why = Object.fromEntries(skipped.map((s) => [s.name, s.why]))
    assert.match(why.product_backlog, /read the source/)
    assert.match(why.vendor_video_sla, /a person maintains/)
    assert.match(why.restricted_source, /deliberately out of reach/)
    assert.equal(why.cohort_scheduling_flow, 'no copy in this repo, read the source')
  })
})

describe('the fingerprint — reading it back out', () => {
  let dir

  before(() => {
    dir = mkdtempSync(join(tmpdir(), 'refresh-fp-'))
    process.chdir(dir)
  })

  test('a file that does not exist has no fingerprint', () => {
    assert.equal(readFingerprint(join(dir, 'nope.md')), null)
  })

  test('a file generated before fingerprints existed has none either', () => {
    // The pre-fingerprint banner shape. This must read as "cannot compare" rather than
    // throwing or, worse, matching something — an unreadable fingerprint has to send the
    // source back for a real look, not get silently treated as current.
    const path = join(dir, 'old.md')
    writeFileSync(path, '<!-- Generated from x by y on 2026-08-01. -->\n\n# Old\n')
    assert.equal(readFingerprint(path), null)
  })

  test('a fingerprint round-trips out of the banner', () => {
    const path = join(dir, 'new.md')
    const sha = sha256(DOC_BODY)
    writeFileSync(path, generated(sha, byteLength(DOC_BODY)))
    assert.deepEqual(readFingerprint(path), { sha, bytes: byteLength(DOC_BODY) })
  })

  test('bytes are bytes, not characters', () => {
    // This one cost a real false positive. The H2 planning doc is full of em-dashes, so
    // `String.length` undercounts it by 17 against its actual UTF-8 size — and a banner
    // that labels a character count "bytes" cannot be reconciled with the source it
    // describes. Anything user-visible has to be the real byte length.
    const emdash = 'a — b'
    assert.equal(emdash.length, 5, 'five characters')
    assert.equal(byteLength(emdash), 7, 'seven bytes — the em-dash is three of them')
    assert.notEqual(byteLength(emdash), emdash.length)
  })

  test('the digest is taken over the decoded body, so a BOM cannot change it', () => {
    // fetch().text() strips a UTF-8 BOM and these Google exports ship one. If the digest
    // were taken over the raw response instead, a hand-computed fingerprint would never
    // match and the gate would report CHANGED on every single run.
    const withBom = '﻿' + DOC_BODY
    assert.equal(sha256(withBom.replace(/^﻿/, '')), sha256(DOC_BODY))
  })
})

describe('the run log', () => {
  test('the newest entry goes above the older ones, under the header', () => {
    const existing = ['# Refresh log', '', 'Newest first.', '', '---', '', '## 2026-08-16', '', 'older'].join('\n')
    const out = insertLogEntry(existing, '## 2026-08-19\n\nnewer\n')
    assert.ok(out.indexOf('## 2026-08-19') < out.indexOf('## 2026-08-16'), 'newest first')
    assert.ok(out.indexOf('# Refresh log') < out.indexOf('## 2026-08-19'), 'below the header')
    assert.match(out, /older/, 'and it never edits what was already there')
  })

  test('an entry names the run, the counts, and what actually moved', () => {
    const entry = renderLogEntry({
      today: '2026-08-19',
      unchanged: [{ name: 'cohort_calendar', file: 'team/_generated/cohort-calendar.md' }],
      changed: [{
        name: 'h2_planning',
        file: 'team/_generated/h2-planning.md',
        wasSha: 'a'.repeat(64),
        nowSha: 'b'.repeat(64),
        wasBytes: 4000,
        nowBytes: 4400,
      }],
      missing: [],
      skipped: [{ name: 'restricted_source', why: 'deliberately out of reach' }],
      failed: [{ name: 'cohort_x', why: 'got a Google sign-in page — the file is not link-shared' }],
      runUrl: 'https://github.com/o/r/actions/runs/1',
    })
    assert.match(entry, /^## 2026-08-19 — pipeline$/m)
    assert.match(entry, /4 checked — 1 unchanged, 1 changed, 0 missing, 1 skipped by design, 1 failed/)
    assert.match(entry, /\*\*CHANGED\*\* — `h2_planning`/)
    assert.match(entry, /4000 → 4400 bytes \(\+10%\)/, 'the magnitude of the change, not just that it changed')
    assert.match(entry, /sha256 aaaaaaaa… → bbbbbbbb…/)
    assert.match(entry, /\*\*FAILED\*\* — `cohort_x`/)
    assert.match(entry, /Unchanged: `cohort_calendar`\./, 'the quiet ones collapse to one line')
    assert.match(entry, /actions\/runs\/1/)
  })

  test('a run where nothing moved says so in one line, not a block per source', () => {
    const entry = renderLogEntry({
      today: '2026-08-19',
      unchanged: [
        { name: 'h2_planning', file: 'a.md' },
        { name: 'cohort_calendar', file: 'b.md' },
      ],
      changed: [],
      missing: [],
      skipped: [{ name: 'product_backlog', why: 'no copy in this repo, read the source' }],
      failed: [],
    })
    assert.match(entry, /Nothing moved\. Every cached copy still matches its source\./)
    assert.equal(entry.includes('**CHANGED**'), false)
    assert.ok(entry.split('\n').length < 12, 'a quiet run must stay short — this is the common case')
  })

  test('a dry run leaves no entry — it did not change anything', async () => {
    const dir = mkdtempSync(join(tmpdir(), 'refresh-'))
    process.chdir(dir)
    writeFileSync(join(dir, 'context-manifest.yaml'), manifest('https://127.0.0.1:1/unused'))
    mkdirSync(join(dir, 'team/_generated'), { recursive: true })
    const { logged } = await check({ dryRun: true, today: '2026-08-19' })
    assert.equal(logged, false)
    assert.equal(existsSync(join(dir, 'team/_generated/refresh-log.md')), false)
  })
})

describe('a real run, against a real server', () => {
  let server
  let url
  let dir

  before(async () => {
    server = createServer((req, res) => {
      if (req.url === '/doc') {
        res.writeHead(200, { 'content-type': 'text/plain' })
        res.end(DOC_BODY)
        return
      }
      if (req.url === '/signin') {
        res.writeHead(200, { 'content-type': 'text/html' })
        res.end('<!DOCTYPE html><html><body><a href="https://accounts.google.com/">Sign in</a></body></html>')
        return
      }
      res.writeHead(404)
      res.end('nope')
    })
    await new Promise((r) => server.listen(0, '127.0.0.1', r))
    url = `http://127.0.0.1:${server.address().port}`
  })

  after(() => server.close())

  const setup = () => {
    dir = mkdtempSync(join(tmpdir(), 'refresh-'))
    process.chdir(dir)
    mkdirSync(join(dir, 'team/_generated'), { recursive: true })
    writeFileSync(join(dir, 'context-manifest.yaml'), manifest(`${url}/doc`))
    return dir
  }

  test('a matching fingerprint is UNCHANGED, and nothing is rewritten', async () => {
    // The whole design in one assertion: byte-identical source means the copy is still
    // accurate, so the file must come back untouched — same mtime-irrelevant bytes, and
    // no regeneration. This is the common case and the one that has to stay free.
    const d = setup()
    const target = join(d, 'team/_generated/h2-planning.md')
    const body = generated(sha256(DOC_BODY), DOC_BODY.length)
    writeFileSync(target, body)

    const { unchanged, changed, missing } = await check({ dryRun: true, today: '2026-08-19' })

    assert.equal(unchanged.length, 1)
    assert.equal(unchanged[0].name, 'h2_planning')
    assert.equal(changed.length, 0)
    assert.equal(missing.length, 0)
    assert.equal(readFileSync(target, 'utf8'), body, 'an unchanged source must not rewrite the copy')
  })

  test('a stale fingerprint is CHANGED, and carries both digests', async () => {
    const d = setup()
    writeFileSync(
      join(d, 'team/_generated/h2-planning.md'),
      generated('0'.repeat(64), 999),
    )

    const { changed, unchanged } = await check({ dryRun: true, today: '2026-08-19' })

    assert.equal(unchanged.length, 0)
    assert.equal(changed.length, 1)
    assert.equal(changed[0].name, 'h2_planning')
    assert.equal(changed[0].wasSha, '0'.repeat(64))
    assert.equal(changed[0].nowSha, sha256(DOC_BODY))
    assert.equal(changed[0].wasBytes, 999)
    assert.equal(changed[0].nowBytes, DOC_BODY.length)
  })

  test('no file at all is MISSING, not UNCHANGED', async () => {
    // Deleting a generated file is how you force a regenerate. If that read as unchanged
    // the file would never come back.
    setup()
    const { missing, unchanged } = await check({ dryRun: true, today: '2026-08-19' })
    assert.equal(unchanged.length, 0)
    assert.equal(missing.length, 1)
    assert.equal(missing[0].name, 'h2_planning')
    assert.match(missing[0].why, /does not exist/)
    assert.equal(missing[0].nowSha, sha256(DOC_BODY))
  })

  test('a Google sign-in page is caught as a failure, not fingerprinted as content', async () => {
    // fetch() sees 200 OK. Hashing it would fingerprint the login page and then report
    // the source as unchanged for as long as the login page stayed the same.
    dir = mkdtempSync(join(tmpdir(), 'refresh-'))
    process.chdir(dir)
    mkdirSync(join(dir, 'team/_generated'), { recursive: true })
    writeFileSync(join(dir, 'context-manifest.yaml'), manifest(`${url}/signin`))
    const { failed } = await check({ dryRun: true, today: '2026-08-19' })
    const f = failed.find((x) => x.name === 'h2_planning')
    assert.ok(f)
    assert.match(f.why, /not link-shared/)
  })

  test('a full run needs no API key, and still writes the log', async () => {
    // The script no longer calls a model, so there is nothing left for a credential to
    // unlock. A run with no key in the environment must be an ordinary, complete run.
    delete process.env.ANTHROPIC_API_KEY
    const d = setup()
    writeFileSync(
      join(d, 'team/_generated/h2-planning.md'),
      generated(sha256(DOC_BODY), DOC_BODY.length),
    )

    const { failed, logged, report } = await check({ today: '2026-08-19' })

    assert.equal(failed.length, 0, 'a missing key is not a failure any more — nothing needs one')
    assert.equal(logged, true)
    assert.equal(/ANTHROPIC_API_KEY/.test(report), false, 'nothing should mention a key')

    const log = readFileSync(join(d, 'team/_generated/refresh-log.md'), 'utf8')
    assert.match(log, /## 2026-08-19 — pipeline/)
    assert.match(log, /Nothing moved/)
  })
})
