/**
 * Run: node --test .claude/skills/refresh-index/check.test.mjs
 *
 * Nothing runs these automatically — there is no CI for this any more, on purpose. Run
 * them before trusting a change to the checker.
 *
 * The failure mode being defended against is a check that reports something reassuring
 * when it has no idea: a manifest rule that fails a source it shouldn't, a fingerprint
 * that can never match, an "unchanged" derived from nothing, and a generated summary
 * written somewhere it does not belong.
 *
 * The fetch path is exercised against a real local HTTP server rather than mocked, so
 * a change to the fetch step is caught here rather than in front of somebody.
 */

import { test, describe, before, after } from 'node:test'
import assert from 'node:assert/strict'
import { createServer } from 'node:http'
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, existsSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'

import { parseSources, check, sha256, byteLength, readFingerprint, overdueBy, findManifest } from './check.mjs'

// A manifest shaped like the real one — one cached source, one live pointer, one
// deliberately unreachable, one with a hand-maintained copy. Every skip rule, once.
const manifest = (fetchUrl) => `
team: webapp

sources:
  h2_planning:
    canonical: "https://docs.example/doc"
    type: google_doc
    owner: "VP Product — not this team"
    reachable: true
    fetch: "${fetchUrl}"
    refresh: quarterly
    summarize_to: team/_generated/h2-planning.md
    last_confirmed: 2026-08-05
    notes: >
      Authored a level up. Regenerate rather than editing in place —
      maintaining a second copy of somebody else's document is a race you lose.

  cohort_scheduling_flow:
    canonical: "https://figma.example/file"
    type: figma
    owner: "Ines Okafor (Design)"
    reachable: true # via Figma MCP
    refresh: live
    last_confirmed: 2026-08-05

  product_backlog:
    canonical: "https://jira.example/board"
    type: jira_project
    reachable: true
    last_confirmed: 2026-08-16

  vendor_video_sla:
    canonical: "vendor portal, SSO only — no API"
    type: vendor_portal
    reachable: false
    copy_of_record: insights/vendor-video-sla-2026-q3.md
    refresh: quarterly

  restricted_source:
    canonical: "Legal, counsel only"
    type: restricted
    reachable: false
    deliberate: true

local:
  - product/decisions/
`

// The body the test server returns from /doc. Kept at module scope because the
// fingerprint tests need to hash exactly what the server will serve.
const DOC_BODY = 'H2 2026 planning. Target: 40% of cohorts full at start. Owner: VP Product.'

// A generated file the way /refresh-index writes one — what matters here is the
// fingerprint line, which is the only state the whole gate keeps.
const generated = (sha, bytes) => `<!-- Generated from https://docs.example/doc
     by /refresh-index on 2026-08-19.
     Source fingerprint: sha256:${sha} (${bytes} bytes)
     Do not edit this file. Edit the source, or the manifest entry that points at it. -->

> **Generated file.** Summarized from the google doc owned by VP Product, on 2026-08-19.

# H2 planning

Target: 40% of cohorts full at start.
`

describe('parseSources — the manifest reader', () => {
  const sources = parseSources(manifest('https://example.test/doc'))

  test('reads every source and stops at the next top-level key', () => {
    assert.deepEqual(Object.keys(sources), [
      'h2_planning',
      'cohort_scheduling_flow',
      'product_backlog',
      'vendor_video_sla',
      'restricted_source',
    ])
  })

  test('an inline comment is not part of the value', () => {
    // `reachable: true # via Figma MCP` has to come back as the boolean true, not the
    // string "true # via Figma MCP", which is truthy and would silently pass every check.
    assert.equal(sources.cohort_scheduling_flow.reachable, true)
    assert.equal(sources.restricted_source.reachable, false)
    assert.equal(sources.restricted_source.deliberate, true)
  })

  test('a folded block comes back as one line', () => {
    assert.match(sources.h2_planning.notes, /^Authored a level up\..*race you lose\.$/)
  })
})

describe('the cached-or-pointed-at rule', () => {
  let dir

  before(() => {
    dir = mkdtempSync(join(tmpdir(), 'refresh-'))
    process.chdir(dir)
  })

  const setup = (yaml) => {
    writeFileSync(join(dir, 'context-manifest.yaml'), yaml)
    mkdirSync(join(dir, 'team/_generated'), { recursive: true })
  }

  test('`refresh: live` on a pointed-at source is correct, not a failure', async () => {
    // This is the bug that kept the pipeline from ever opening a PR. `live` is the one
    // refresh value that means "there is deliberately no copy" — demanding a path from
    // it inverts what it says, and the exit code it produced killed the PR step.
    setup(manifest('https://127.0.0.1:1/unused'))
    const { failed } = await check({ today: '2026-08-19' })
    assert.equal(
      failed.some((f) => f.name === 'cohort_scheduling_flow'),
      false,
      'a live pointer must not be reported as a manifest error',
    )
  })

  test('a real cadence with nowhere to write still fails', async () => {
    setup(manifest('https://127.0.0.1:1/unused').replace('refresh: live', 'refresh: weekly'))
    const { failed } = await check({ today: '2026-08-19' })
    const f = failed.find((x) => x.name === 'cohort_scheduling_flow')
    assert.ok(f, 'a cadence on a source with no path is somebody assuming a copy exists')
    assert.match(f.why, /names no file in this repo/)
  })

  test('each kind of skip says which kind it is', async () => {
    setup(manifest('https://127.0.0.1:1/unused'))
    const { skipped } = await check({ today: '2026-08-19' })
    const why = Object.fromEntries(skipped.map((s) => [s.name, s.why]))
    assert.match(why.product_backlog, /read the source/)
    assert.match(why.vendor_video_sla, /a person maintains/)
    assert.match(why.restricted_source, /deliberately out of reach/)
    assert.equal(why.cohort_scheduling_flow, 'no copy in this repo, read the source')
  })
})

describe('generated summaries stay inside team/_generated/', () => {
  let dir

  before(() => {
    dir = mkdtempSync(join(tmpdir(), 'refresh-guard-'))
    process.chdir(dir)
    mkdirSync(join(dir, 'team/_generated'), { recursive: true })
  })

  test('a summarize_to aimed at a discipline folder is a manifest error', async () => {
    // The one that matters. A refresh rewriting insights/definitions.md would be
    // overwriting a file whose knowledge belongs to a named person who is not in the room
    // when the skill runs — and guessed content there is worse than an empty file,
    // because the lead reading it later cannot tell which lines to trust.
    writeFileSync(
      join(dir, 'context-manifest.yaml'),
      manifest('https://127.0.0.1:1/unused').replace(
        'summarize_to: team/_generated/h2-planning.md',
        'summarize_to: insights/definitions.md',
      ),
    )
    const { failed } = await check({ today: '2026-08-19' })
    const f = failed.find((x) => x.name === 'h2_planning')
    assert.ok(f, 'writing outside team/_generated/ must not be allowed to pass quietly')
    assert.match(f.why, /outside `team\/_generated\/`/)
    assert.match(f.why, /filled with its lead/)
  })

  test('team/_generated/ itself is fine', async () => {
    writeFileSync(join(dir, 'context-manifest.yaml'), manifest('https://127.0.0.1:1/unused'))
    const { failed } = await check({ today: '2026-08-19' })
    assert.equal(failed.some((f) => /outside/.test(f.why)), false)
  })
})

describe('finding the manifest from wherever you happen to be', () => {
  let root

  before(() => {
    root = mkdtempSync(join(tmpdir(), 'refresh-find-'))
    mkdirSync(join(root, 'a/b/c'), { recursive: true })
    writeFileSync(join(root, 'context-manifest.yaml'), manifest('https://127.0.0.1:1/x'))
  })

  test('walks up from a subdirectory', () => {
    assert.equal(findManifest(join(root, 'a/b/c')), join(root, 'context-manifest.yaml'))
  })

  test('finds it in the directory itself', () => {
    assert.equal(findManifest(root), join(root, 'context-manifest.yaml'))
  })

  test('says what it looked for when there is none', () => {
    // The old behaviour was a bare ENOENT naming a relative path, which tells a
    // first-time reader nothing. The message has to name the directory it started from.
    const orphan = mkdtempSync(join(tmpdir(), 'refresh-orphan-'))
    assert.throws(() => findManifest(orphan), (err) => {
      assert.match(err.message, /no context-manifest\.yaml/)
      assert.match(err.message, /or any directory above it/)
      return true
    })
  })
})

describe('a source that will not hash the same twice is caught before it churns', () => {
  let server, url, dir, flip

  before(async () => {
    flip = 0
    server = createServer((req, res) => {
      res.writeHead(200, { 'content-type': 'text/plain' })
      // /wobbly returns something different on every call — an export carrying a
      // timestamp, or a search index normalising differently between reads.
      if (req.url === '/wobbly') return res.end(`${DOC_BODY} [generated ${flip++}]`)
      res.end(DOC_BODY)
    })
    await new Promise((r) => server.listen(0, '127.0.0.1', r))
    url = `http://127.0.0.1:${server.address().port}`
  })

  after(() => server.close())

  test('two disagreeing fetches mean no fingerprint gets written', async () => {
    // Writing one would make every future run report CHANGED, forever, for a source
    // nobody actually edited — the exact churn this whole mechanism exists to prevent.
    dir = mkdtempSync(join(tmpdir(), 'refresh-wobble-'))
    mkdirSync(join(dir, 'team/_generated'), { recursive: true })
    writeFileSync(join(dir, 'context-manifest.yaml'), manifest(`${url}/wobbly`))

    const { unstable, missing } = await check({ manifestPath: join(dir, 'context-manifest.yaml'), today: '2026-08-19' })

    assert.equal(unstable.length, 1, 'the source must be reported as unfingerprintable')
    assert.equal(unstable[0].name, 'h2_planning')
    assert.notEqual(unstable[0].first, unstable[0].second)
    assert.equal(missing.length, 0, 'and it must NOT fall through to a normal first write')
  })

  test('a stable source is unaffected', async () => {
    dir = mkdtempSync(join(tmpdir(), 'refresh-stable-'))
    mkdirSync(join(dir, 'team/_generated'), { recursive: true })
    writeFileSync(join(dir, 'context-manifest.yaml'), manifest(`${url}/steady`))

    const { unstable, missing } = await check({ manifestPath: join(dir, 'context-manifest.yaml'), today: '2026-08-19' })

    assert.equal(unstable.length, 0)
    assert.equal(missing.length, 1)
  })
})

describe('a source only a connector can reach', () => {
  let dir

  before(() => {
    dir = mkdtempSync(join(tmpdir(), 'refresh-via-'))
    mkdirSync(join(dir, 'team/_generated'), { recursive: true })
  })

  test('fetch_via is reported as needing the skill, never skipped quietly', async () => {
    // This script cannot call an MCP server. Skipping such a source silently would let a
    // cached copy sit unchecked indefinitely while the report looked clean — which is the
    // exact silent failure the whole mechanism exists to prevent. It has to say so.
    writeFileSync(
      join(dir, 'context-manifest.yaml'),
      manifest('https://127.0.0.1:1/unused').replace(
        '    fetch: "https://127.0.0.1:1/unused"',
        '    fetch_via: glean',
      ),
    )
    const { manual, skipped, unchanged } = await check({
      manifestPath: join(dir, 'context-manifest.yaml'), today: '2026-08-19',
    })

    assert.equal(manual.length, 1)
    assert.equal(manual[0].name, 'h2_planning')
    assert.equal(manual[0].via, 'glean')
    assert.equal(manual[0].prior, null, 'no fingerprint yet, so the skill does a first pass')
    assert.equal(unchanged.length, 0, 'it must never be reported as up to date')
    assert.equal(skipped.some((s) => s.name === 'h2_planning'), false)
  })

  test('an existing fingerprint is handed to the skill to compare against', async () => {
    writeFileSync(
      join(dir, 'team/_generated/h2-planning.md'),
      generated(sha256(DOC_BODY), byteLength(DOC_BODY)),
    )
    const { manual } = await check({
      manifestPath: join(dir, 'context-manifest.yaml'), today: '2026-08-19',
    })
    assert.equal(manual[0].prior.sha, sha256(DOC_BODY))
  })
})

describe('an overdue hand-maintained export is a finding', () => {
  test('inside its cadence, nothing is said', () => {
    assert.equal(overdueBy('quarterly', '2026-08-04', '2026-08-19'), null)
  })

  test('past its cadence, it is reported with the gap', () => {
    // There is no upstream to compare against — that is why a person exports it. So the
    // only checkable promise is whether the export happened, and a quarterly export that
    // last landed in January is exactly the finding this entry shape exists to surface.
    const late = overdueBy('quarterly', '2026-01-04', '2026-08-19')
    assert.ok(late)
    assert.equal(late.window, 92)
    assert.ok(late.days > 92, 'and it says how far past, not just that it is past')
  })

  test('as-needed has no schedule, so it can never be late', () => {
    assert.equal(overdueBy('as-needed', '2020-01-01', '2026-08-19'), null)
  })

  test('nothing to measure from is not a finding either', () => {
    // A missing last_confirmed means nobody has ever confirmed it, which is a different
    // problem and belongs to the pointer check, not to this one. Reporting it as overdue
    // would put a date on a promise nobody made.
    assert.equal(overdueBy('quarterly', undefined, '2026-08-19'), null)
  })
})

describe('the fingerprint — reading it back out', () => {
  let dir

  before(() => {
    dir = mkdtempSync(join(tmpdir(), 'refresh-fp-'))
    process.chdir(dir)
  })

  test('a file that does not exist has no fingerprint', () => {
    assert.equal(readFingerprint(join(dir, 'nope.md')), null)
  })

  test('a file generated before fingerprints existed has none either', () => {
    // The pre-fingerprint banner shape. This must read as "cannot compare" rather than
    // throwing or, worse, matching something — an unreadable fingerprint has to send the
    // source back for a real look, not get silently treated as current.
    const path = join(dir, 'old.md')
    writeFileSync(path, '<!-- Generated from x by y on 2026-08-01. -->\n\n# Old\n')
    assert.equal(readFingerprint(path), null)
  })

  test('a fingerprint round-trips out of the banner', () => {
    const path = join(dir, 'new.md')
    const sha = sha256(DOC_BODY)
    writeFileSync(path, generated(sha, byteLength(DOC_BODY)))
    assert.deepEqual(readFingerprint(path), { sha, bytes: byteLength(DOC_BODY) })
  })

  test('bytes are bytes, not characters', () => {
    // This one cost a real false positive. The H2 planning doc is full of em-dashes, so
    // `String.length` undercounts it by 17 against its actual UTF-8 size — and a banner
    // that labels a character count "bytes" cannot be reconciled with the source it
    // describes. Anything user-visible has to be the real byte length.
    const emdash = 'a — b'
    assert.equal(emdash.length, 5, 'five characters')
    assert.equal(byteLength(emdash), 7, 'seven bytes — the em-dash is three of them')
    assert.notEqual(byteLength(emdash), emdash.length)
  })

  test('the digest is taken over the decoded body, so a BOM cannot change it', () => {
    // fetch().text() strips a UTF-8 BOM and these Google exports ship one. If the digest
    // were taken over the raw response instead, a hand-computed fingerprint would never
    // match and the gate would report CHANGED on every single run.
    const withBom = '﻿' + DOC_BODY
    assert.equal(sha256(withBom.replace(/^﻿/, '')), sha256(DOC_BODY))
  })
})

describe('a real run, against a real server', () => {
  let server
  let url
  let dir

  before(async () => {
    server = createServer((req, res) => {
      if (req.url === '/doc') {
        res.writeHead(200, { 'content-type': 'text/plain' })
        res.end(DOC_BODY)
        return
      }
      if (req.url === '/signin') {
        res.writeHead(200, { 'content-type': 'text/html' })
        res.end('<!DOCTYPE html><html><body><a href="https://accounts.google.com/">Sign in</a></body></html>')
        return
      }
      res.writeHead(404)
      res.end('nope')
    })
    await new Promise((r) => server.listen(0, '127.0.0.1', r))
    url = `http://127.0.0.1:${server.address().port}`
  })

  after(() => server.close())

  const setup = () => {
    dir = mkdtempSync(join(tmpdir(), 'refresh-'))
    process.chdir(dir)
    mkdirSync(join(dir, 'team/_generated'), { recursive: true })
    writeFileSync(join(dir, 'context-manifest.yaml'), manifest(`${url}/doc`))
    return dir
  }

  test('a matching fingerprint is UNCHANGED, and nothing is rewritten', async () => {
    // The whole design in one assertion: byte-identical source means the copy is still
    // accurate, so the file must come back untouched — same mtime-irrelevant bytes, and
    // no regeneration. This is the common case and the one that has to stay free.
    const d = setup()
    const target = join(d, 'team/_generated/h2-planning.md')
    const body = generated(sha256(DOC_BODY), DOC_BODY.length)
    writeFileSync(target, body)

    const { unchanged, changed, missing } = await check({ today: '2026-08-19' })

    assert.equal(unchanged.length, 1)
    assert.equal(unchanged[0].name, 'h2_planning')
    assert.equal(changed.length, 0)
    assert.equal(missing.length, 0)
    assert.equal(readFileSync(target, 'utf8'), body, 'an unchanged source must not rewrite the copy')
  })

  test('a stale fingerprint is CHANGED, and carries both digests', async () => {
    const d = setup()
    writeFileSync(
      join(d, 'team/_generated/h2-planning.md'),
      generated('0'.repeat(64), 999),
    )

    const { changed, unchanged } = await check({ today: '2026-08-19' })

    assert.equal(unchanged.length, 0)
    assert.equal(changed.length, 1)
    assert.equal(changed[0].name, 'h2_planning')
    assert.equal(changed[0].wasSha, '0'.repeat(64))
    assert.equal(changed[0].nowSha, sha256(DOC_BODY))
    assert.equal(changed[0].wasBytes, 999)
    assert.equal(changed[0].nowBytes, DOC_BODY.length)
  })

  test('no file at all is MISSING, not UNCHANGED', async () => {
    // Deleting a generated file is how you force a regenerate. If that read as unchanged
    // the file would never come back.
    setup()
    const { missing, unchanged } = await check({ today: '2026-08-19' })
    assert.equal(unchanged.length, 0)
    assert.equal(missing.length, 1)
    assert.equal(missing[0].name, 'h2_planning')
    assert.match(missing[0].why, /does not exist/)
    assert.equal(missing[0].nowSha, sha256(DOC_BODY))
  })

  test('a Google sign-in page is caught as a failure, not fingerprinted as content', async () => {
    // fetch() sees 200 OK. Hashing it would fingerprint the login page and then report
    // the source as unchanged for as long as the login page stayed the same.
    dir = mkdtempSync(join(tmpdir(), 'refresh-'))
    process.chdir(dir)
    mkdirSync(join(dir, 'team/_generated'), { recursive: true })
    writeFileSync(join(dir, 'context-manifest.yaml'), manifest(`${url}/signin`))
    const { failed } = await check({ today: '2026-08-19' })
    const f = failed.find((x) => x.name === 'h2_planning')
    assert.ok(f)
    assert.match(f.why, /not link-shared/)
  })

  test('a full run needs no credential and writes nothing at all', async () => {
    // Two properties in one, and both are load-bearing. There is no model call left, so
    // no key is needed. And the script is read-only: the skill is the single writer, so
    // one run produces one log entry written by the thing that also made the judgment,
    // rather than two entries disagreeing about how much they understood.
    delete process.env.ANTHROPIC_API_KEY
    const d = setup()
    writeFileSync(
      join(d, 'team/_generated/h2-planning.md'),
      generated(sha256(DOC_BODY), byteLength(DOC_BODY)),
    )

    const { failed, unchanged, report } = await check({ today: '2026-08-19' })

    assert.equal(failed.length, 0, 'a missing key is not a failure — nothing needs one')
    assert.equal(unchanged.length, 1)
    assert.equal(/ANTHROPIC_API_KEY/.test(report), false, 'nothing should mention a key')
    assert.equal(
      existsSync(join(d, 'team/_generated/refresh-log.md')),
      false,
      'the checker does not write the log — the skill does',
    )
  })
})

describe('the shipped template and this copy have not drifted', () => {
  // Three copies of this skill exist: the canonical one inside stand-up-your-repo's
  // templates (what ships to every new team), this installed instance, and whatever each
  // team ends up with. Nothing keeps them identical, so a bug fixed in one silently
  // persists in the others. This makes that loud — but only when both repos happen to be
  // checked out next to each other, so it never fails for someone who has only one.
  const template = join(
    import.meta.dirname, '../../../../nyt-context-cohort',
    '.claude/skills/stand-up-your-repo/templates/refresh-index',
  )
  const available = existsSync(template)

  test('check.mjs is byte-identical to the canonical copy', { skip: !available && 'cohort repo not checked out alongside' }, () => {
    assert.equal(
      readFileSync(join(import.meta.dirname, 'check.mjs'), 'utf8'),
      readFileSync(join(template, 'check.mjs'), 'utf8'),
      'check.mjs has drifted from the template that ships. Re-sync — see the header comment.',
    )
  })

  test('check.test.mjs is byte-identical to the canonical copy', { skip: !available && 'cohort repo not checked out alongside' }, () => {
    assert.equal(
      readFileSync(join(import.meta.dirname, 'check.test.mjs'), 'utf8'),
      readFileSync(join(template, 'check.test.mjs'), 'utf8'),
      'check.test.mjs has drifted from the template that ships. Re-sync — see the header comment.',
    )
  })
})
